/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DoaRouteRouteImport } from './routes/doa.route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoaIndexRouteImport } from './routes/doa.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ListListIdRouteImport } from './routes/list.$listId'
import { Route as DoaSlugRouteImport } from './routes/doa.$slug'
import { Route as DashboardSavedListsRouteImport } from './routes/dashboard.saved-lists'
import { Route as DashboardSavedDuasRouteImport } from './routes/dashboard.saved-duas'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardDoaImageRouteImport } from './routes/dashboard.doa-image'
import { Route as DashboardCreateDoaListRouteImport } from './routes/dashboard.create-doa-list'
import { Route as ApiShopeeReferralsRouteImport } from './routes/api/shopee-referrals'
import { Route as ApiDoaRouteImport } from './routes/api/doa'
import { Route as ApiShopeeOgSplatRouteImport } from './routes/api/shopee-og/$'
import { Route as ApiDoaRandomRouteImport } from './routes/api/doa/random'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DoaRouteRoute = DoaRouteRouteImport.update({
  id: '/doa',
  path: '/doa',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoaIndexRoute = DoaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoaRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ListListIdRoute = ListListIdRouteImport.update({
  id: '/list/$listId',
  path: '/list/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const DoaSlugRoute = DoaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DoaRouteRoute,
} as any)
const DashboardSavedListsRoute = DashboardSavedListsRouteImport.update({
  id: '/saved-lists',
  path: '/saved-lists',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSavedDuasRoute = DashboardSavedDuasRouteImport.update({
  id: '/saved-duas',
  path: '/saved-duas',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDoaImageRoute = DashboardDoaImageRouteImport.update({
  id: '/doa-image',
  path: '/doa-image',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCreateDoaListRoute = DashboardCreateDoaListRouteImport.update({
  id: '/create-doa-list',
  path: '/create-doa-list',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiShopeeReferralsRoute = ApiShopeeReferralsRouteImport.update({
  id: '/api/shopee-referrals',
  path: '/api/shopee-referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDoaRoute = ApiDoaRouteImport.update({
  id: '/api/doa',
  path: '/api/doa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopeeOgSplatRoute = ApiShopeeOgSplatRouteImport.update({
  id: '/api/shopee-og/$',
  path: '/api/shopee-og/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDoaRandomRoute = ApiDoaRandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => ApiDoaRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/doa': typeof DoaRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/api/doa': typeof ApiDoaRouteWithChildren
  '/api/shopee-referrals': typeof ApiShopeeReferralsRoute
  '/dashboard/create-doa-list': typeof DashboardCreateDoaListRoute
  '/dashboard/doa-image': typeof DashboardDoaImageRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/saved-duas': typeof DashboardSavedDuasRoute
  '/dashboard/saved-lists': typeof DashboardSavedListsRoute
  '/doa/$slug': typeof DoaSlugRoute
  '/list/$listId': typeof ListListIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/doa/': typeof DoaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/doa/random': typeof ApiDoaRandomRoute
  '/api/shopee-og/$': typeof ApiShopeeOgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/api/doa': typeof ApiDoaRouteWithChildren
  '/api/shopee-referrals': typeof ApiShopeeReferralsRoute
  '/dashboard/create-doa-list': typeof DashboardCreateDoaListRoute
  '/dashboard/doa-image': typeof DashboardDoaImageRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/saved-duas': typeof DashboardSavedDuasRoute
  '/dashboard/saved-lists': typeof DashboardSavedListsRoute
  '/doa/$slug': typeof DoaSlugRoute
  '/list/$listId': typeof ListListIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/doa': typeof DoaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/doa/random': typeof ApiDoaRandomRoute
  '/api/shopee-og/$': typeof ApiShopeeOgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/doa': typeof DoaRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/api/doa': typeof ApiDoaRouteWithChildren
  '/api/shopee-referrals': typeof ApiShopeeReferralsRoute
  '/dashboard/create-doa-list': typeof DashboardCreateDoaListRoute
  '/dashboard/doa-image': typeof DashboardDoaImageRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/saved-duas': typeof DashboardSavedDuasRoute
  '/dashboard/saved-lists': typeof DashboardSavedListsRoute
  '/doa/$slug': typeof DoaSlugRoute
  '/list/$listId': typeof ListListIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/doa/': typeof DoaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/doa/random': typeof ApiDoaRandomRoute
  '/api/shopee-og/$': typeof ApiShopeeOgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/doa'
    | '/about'
    | '/admin'
    | '/contact'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/api/doa'
    | '/api/shopee-referrals'
    | '/dashboard/create-doa-list'
    | '/dashboard/doa-image'
    | '/dashboard/referrals'
    | '/dashboard/saved-duas'
    | '/dashboard/saved-lists'
    | '/doa/$slug'
    | '/list/$listId'
    | '/dashboard/'
    | '/doa/'
    | '/api/auth/$'
    | '/api/doa/random'
    | '/api/shopee-og/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/api/doa'
    | '/api/shopee-referrals'
    | '/dashboard/create-doa-list'
    | '/dashboard/doa-image'
    | '/dashboard/referrals'
    | '/dashboard/saved-duas'
    | '/dashboard/saved-lists'
    | '/doa/$slug'
    | '/list/$listId'
    | '/dashboard'
    | '/doa'
    | '/api/auth/$'
    | '/api/doa/random'
    | '/api/shopee-og/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/doa'
    | '/about'
    | '/admin'
    | '/contact'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/api/doa'
    | '/api/shopee-referrals'
    | '/dashboard/create-doa-list'
    | '/dashboard/doa-image'
    | '/dashboard/referrals'
    | '/dashboard/saved-duas'
    | '/dashboard/saved-lists'
    | '/doa/$slug'
    | '/list/$listId'
    | '/dashboard/'
    | '/doa/'
    | '/api/auth/$'
    | '/api/doa/random'
    | '/api/shopee-og/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  DoaRouteRoute: typeof DoaRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  TermsRoute: typeof TermsRoute
  ApiDoaRoute: typeof ApiDoaRouteWithChildren
  ApiShopeeReferralsRoute: typeof ApiShopeeReferralsRoute
  ListListIdRoute: typeof ListListIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiShopeeOgSplatRoute: typeof ApiShopeeOgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doa': {
      id: '/doa'
      path: '/doa'
      fullPath: '/doa'
      preLoaderRoute: typeof DoaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doa/': {
      id: '/doa/'
      path: '/'
      fullPath: '/doa/'
      preLoaderRoute: typeof DoaIndexRouteImport
      parentRoute: typeof DoaRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/list/$listId': {
      id: '/list/$listId'
      path: '/list/$listId'
      fullPath: '/list/$listId'
      preLoaderRoute: typeof ListListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doa/$slug': {
      id: '/doa/$slug'
      path: '/$slug'
      fullPath: '/doa/$slug'
      preLoaderRoute: typeof DoaSlugRouteImport
      parentRoute: typeof DoaRouteRoute
    }
    '/dashboard/saved-lists': {
      id: '/dashboard/saved-lists'
      path: '/saved-lists'
      fullPath: '/dashboard/saved-lists'
      preLoaderRoute: typeof DashboardSavedListsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/saved-duas': {
      id: '/dashboard/saved-duas'
      path: '/saved-duas'
      fullPath: '/dashboard/saved-duas'
      preLoaderRoute: typeof DashboardSavedDuasRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/doa-image': {
      id: '/dashboard/doa-image'
      path: '/doa-image'
      fullPath: '/dashboard/doa-image'
      preLoaderRoute: typeof DashboardDoaImageRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/create-doa-list': {
      id: '/dashboard/create-doa-list'
      path: '/create-doa-list'
      fullPath: '/dashboard/create-doa-list'
      preLoaderRoute: typeof DashboardCreateDoaListRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/shopee-referrals': {
      id: '/api/shopee-referrals'
      path: '/api/shopee-referrals'
      fullPath: '/api/shopee-referrals'
      preLoaderRoute: typeof ApiShopeeReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doa': {
      id: '/api/doa'
      path: '/api/doa'
      fullPath: '/api/doa'
      preLoaderRoute: typeof ApiDoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopee-og/$': {
      id: '/api/shopee-og/$'
      path: '/api/shopee-og/$'
      fullPath: '/api/shopee-og/$'
      preLoaderRoute: typeof ApiShopeeOgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doa/random': {
      id: '/api/doa/random'
      path: '/random'
      fullPath: '/api/doa/random'
      preLoaderRoute: typeof ApiDoaRandomRouteImport
      parentRoute: typeof ApiDoaRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardCreateDoaListRoute: typeof DashboardCreateDoaListRoute
  DashboardDoaImageRoute: typeof DashboardDoaImageRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardSavedDuasRoute: typeof DashboardSavedDuasRoute
  DashboardSavedListsRoute: typeof DashboardSavedListsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCreateDoaListRoute: DashboardCreateDoaListRoute,
  DashboardDoaImageRoute: DashboardDoaImageRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardSavedDuasRoute: DashboardSavedDuasRoute,
  DashboardSavedListsRoute: DashboardSavedListsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface DoaRouteRouteChildren {
  DoaSlugRoute: typeof DoaSlugRoute
  DoaIndexRoute: typeof DoaIndexRoute
}

const DoaRouteRouteChildren: DoaRouteRouteChildren = {
  DoaSlugRoute: DoaSlugRoute,
  DoaIndexRoute: DoaIndexRoute,
}

const DoaRouteRouteWithChildren = DoaRouteRoute._addFileChildren(
  DoaRouteRouteChildren,
)

interface ApiDoaRouteChildren {
  ApiDoaRandomRoute: typeof ApiDoaRandomRoute
}

const ApiDoaRouteChildren: ApiDoaRouteChildren = {
  ApiDoaRandomRoute: ApiDoaRandomRoute,
}

const ApiDoaRouteWithChildren =
  ApiDoaRoute._addFileChildren(ApiDoaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  DoaRouteRoute: DoaRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  TermsRoute: TermsRoute,
  ApiDoaRoute: ApiDoaRouteWithChildren,
  ApiShopeeReferralsRoute: ApiShopeeReferralsRoute,
  ListListIdRoute: ListListIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiShopeeOgSplatRoute: ApiShopeeOgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
