/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateDoaListRouteImport } from './routes/create-doa-list'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DoaRouteRouteImport } from './routes/doa.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoaIndexRouteImport } from './routes/doa.index'
import { Route as DoaSlugRouteImport } from './routes/doa.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateDoaListRoute = CreateDoaListRouteImport.update({
  id: '/create-doa-list',
  path: '/create-doa-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DoaRouteRoute = DoaRouteRouteImport.update({
  id: '/doa',
  path: '/doa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoaIndexRoute = DoaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoaRouteRoute,
} as any)
const DoaSlugRoute = DoaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DoaRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doa': typeof DoaRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/create-doa-list': typeof CreateDoaListRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/doa/$slug': typeof DoaSlugRoute
  '/doa/': typeof DoaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/create-doa-list': typeof CreateDoaListRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/doa/$slug': typeof DoaSlugRoute
  '/doa': typeof DoaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doa': typeof DoaRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/create-doa-list': typeof CreateDoaListRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/doa/$slug': typeof DoaSlugRoute
  '/doa/': typeof DoaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doa'
    | '/about'
    | '/contact'
    | '/create-doa-list'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/signup'
    | '/terms'
    | '/doa/$slug'
    | '/doa/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/create-doa-list'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/signup'
    | '/terms'
    | '/doa/$slug'
    | '/doa'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/doa'
    | '/about'
    | '/contact'
    | '/create-doa-list'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/signup'
    | '/terms'
    | '/doa/$slug'
    | '/doa/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoaRouteRoute: typeof DoaRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CreateDoaListRoute: typeof CreateDoaListRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-doa-list': {
      id: '/create-doa-list'
      path: '/create-doa-list'
      fullPath: '/create-doa-list'
      preLoaderRoute: typeof CreateDoaListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doa': {
      id: '/doa'
      path: '/doa'
      fullPath: '/doa'
      preLoaderRoute: typeof DoaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doa/': {
      id: '/doa/'
      path: '/'
      fullPath: '/doa/'
      preLoaderRoute: typeof DoaIndexRouteImport
      parentRoute: typeof DoaRouteRoute
    }
    '/doa/$slug': {
      id: '/doa/$slug'
      path: '/$slug'
      fullPath: '/doa/$slug'
      preLoaderRoute: typeof DoaSlugRouteImport
      parentRoute: typeof DoaRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DoaRouteRouteChildren {
  DoaSlugRoute: typeof DoaSlugRoute
  DoaIndexRoute: typeof DoaIndexRoute
}

const DoaRouteRouteChildren: DoaRouteRouteChildren = {
  DoaSlugRoute: DoaSlugRoute,
  DoaIndexRoute: DoaIndexRoute,
}

const DoaRouteRouteWithChildren = DoaRouteRoute._addFileChildren(
  DoaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoaRouteRoute: DoaRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CreateDoaListRoute: CreateDoaListRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
